sudo: false

language: java

env:
        global:
        - MAKE=make
        - CLASS_DEST=${TRAVIS_BUILD_DIR}

branches:
        only:
        - master

addons:
        apt:
                packages: &common_packages
                - automake
                - build-essential

script:
        - cd coniks_server; ${MAKE}
        - cd ..
        - cd coniks_test_client; ${MAKE}
        - cd ..

notifications:
  # Email notifications are disabled to not annoy anyb ody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false